### ISSUE TITLE
Hahmo voi hävitä kentästä

### ISSUE THREAD

**Issue by vuoristo** [Eino050/Lyrick#1]
Kun pelaaja kävelee kentän reunaan, hahmo voi mennä reunan taakse ja hävitä näkyvistä.

![image](https://github.com/Eino050/Lyrick/assets/4975769/f9077af5-651f-4094-be5f-087aa859a84f)

**Comment by Eino050** [comment]
Selvä, korjaan tuon vian heti kun ehdin.
